global:
  scrape_interval: 15s  # Scrape metrics every 15 seconds

scrape_configs:
  - job_name: 'nodejs-app'
    static_configs:
      - targets: ['3.145.86.102:3000']  # IP and port of your Node.js app (replace with the actual IP)

