---
- name: Set up Web Servers
  hosts: all
  become: yes
  tasks:
    - name: Install Docker
      apt:
        update_cache: yes
        name: docker.io
        state: present
      when: ansible_os_family == "Debian"

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add ansible user to docker group
      user:
        name: "{{ ansible_user }}"  # Use the Ansible user running the playbook
        groups: docker
        append: yes
      become: yes  # Ensure it's run as a superuser

    - name: Set permissions on Docker socket
      file:
        path: /var/run/docker.sock
        mode: '0666'
        owner: root
        group: docker
      become: yes

    - name: Clone the Node.js web app from GitHub
      git:
        repo: 'https://github.com/artibhoir369/sample-node-app.git'
        dest: /opt/webapp
      become: yes  # Ensure correct permissions

    - name: Check the current user
      command: whoami
      register: current_user
      become: yes  # Ensure it's run as root
  
    - name: Show current user
      debug:
        var: current_user.stdout


    - name: Build Docker image for the Node.js app
      docker_image:
        build:
          path: /opt/webapp  # Corrected path to the directory containing the Dockerfile
          dockerfile: /opt/webapp/Dockerfile  # Explicitly specify the Dockerfile path (optional)
        name: sample-node-app
        tag: latest
        state: present  # Ensure the image is built

    - name: Run the Node.js app in a Docker container
      docker_container:
        name: node-webapp
        image: sample-node-app:latest
        state: started
        restart_policy: always
        ports:
          - "3000:3000"

