---
- name: Set up Web Servers
  hosts: all
  become: yes
  tasks:
    - name: Install Docker
      apt:
        update_cache: yes
        name: docker.io
        state: present
      when: ansible_os_family == "Debian"

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Clone the Node.js web app from GitHub
      git:
        repo: 'https://github.com/artibhoir369/sample-node-app.git'  # Replace with your actual repo URL
        dest: /opt/webapp

    - name: Create Dockerfile for the Node.js app
      copy:
        content: |
          FROM node:14
          WORKDIR /usr/src/app
          COPY package*.json ./
          RUN npm install
          COPY . .
          EXPOSE 3000
          CMD [ "npm", "start" ]
        dest: /opt/webapp/Dockerfile

    - name: Build Docker image for the Node.js app
      docker_image:
        build:
          path: /opt/webapp
        name: sample-node-app
        tag: latest

    - name: Run the Node.js app in a Docker container
      docker_container:
        name: node-webapp
        image: sample-node-app:latest
        state: started
        restart_policy: always
        ports:
          - "3000:3000"  # Exposing port 3000 for the Node.js app

