deploy:
  runs-on: ubuntu-latest
  needs: build_and_test
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set AWS credentials
      run: |
        echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
        echo "AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }}" >> $GITHUB_ENV

    - name: Change directory to infra/aws
      run: cd infra/aws

    - name: Terraform Init and Apply
      run: |
        terraform init
        terraform apply -auto-approve

    - name: Get AWS Public IP
      id: get_public_ip
      run: |
        echo "::set-output name=public_ip::$(terraform output -raw public_ip)"

    - name: Update Ansible Inventory with Public IP
      run: |
        sed -i "s/{{ PUBLIC_IP }}/${{ steps.get_public_ip.outputs.public_ip }}/" ansible/inventory.ini

    - name: Run Ansible Playbook
      run: ansible-playbook -i ansible/inventory.ini ansible/playbook.yml

